"""initial schema

Revision ID: c0962a77e45b
Revises: 
Create Date: 2026-04-02 13:28:28.835948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0962a77e45b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_name', sa.String(length=255), nullable=False),
    sa.Column('chamber', sa.String(length=10), nullable=False),
    sa.Column('committee_code', sa.String(length=20), nullable=True),
    sa.Column('committee_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('congress_number', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('sectors_covered', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_name', 'committee_code', 'congress_number', name='uq_committee_membership')
    )
    op.create_index(op.f('ix_committee_memberships_committee_code'), 'committee_memberships', ['committee_code'], unique=False)
    op.create_index(op.f('ix_committee_memberships_member_name'), 'committee_memberships', ['member_name'], unique=False)
    op.create_table('congressional_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_name', sa.String(length=255), nullable=False),
    sa.Column('chamber', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('party', sa.String(length=20), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('asset_name', sa.String(length=255), nullable=True),
    sa.Column('trade_type', sa.String(length=10), nullable=False),
    sa.Column('amount_min', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('amount_max', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('disclosure_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_name', 'ticker', 'trade_date', 'trade_type', 'amount_min', name='uq_congress_trade')
    )
    op.create_index('ix_congress_member_ticker', 'congressional_trades', ['member_name', 'ticker'], unique=False)
    op.create_index(op.f('ix_congressional_trades_member_name'), 'congressional_trades', ['member_name'], unique=False)
    op.create_index(op.f('ix_congressional_trades_ticker'), 'congressional_trades', ['ticker'], unique=False)
    op.create_index(op.f('ix_congressional_trades_trade_date'), 'congressional_trades', ['trade_date'], unique=False)
    op.create_table('dividend_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('yield_at_announce', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'ex_date', 'amount', name='uq_dividend_event')
    )
    op.create_index(op.f('ix_dividend_events_ticker'), 'dividend_events', ['ticker'], unique=False)
    op.create_table('etf_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_ticker', sa.String(length=10), nullable=False),
    sa.Column('etf_name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('flow_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('aum', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('flow_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etf_ticker', 'date', name='uq_etf_flow')
    )
    op.create_index(op.f('ix_etf_flows_date'), 'etf_flows', ['date'], unique=False)
    op.create_index(op.f('ix_etf_flows_etf_ticker'), 'etf_flows', ['etf_ticker'], unique=False)
    op.create_index(op.f('ix_etf_flows_sector'), 'etf_flows', ['sector'], unique=False)
    op.create_table('event_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('sectors_affected', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insider_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=False),
    sa.Column('filer_name', sa.String(length=255), nullable=False),
    sa.Column('filer_title', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('trade_type', sa.String(length=10), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('price_per_share', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('filing_date', sa.DateTime(), nullable=False),
    sa.Column('filing_url', sa.String(length=512), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik', 'ticker', 'trade_date', 'trade_type', 'shares', name='uq_insider_trade')
    )
    op.create_index(op.f('ix_insider_trades_sector'), 'insider_trades', ['sector'], unique=False)
    op.create_index(op.f('ix_insider_trades_ticker'), 'insider_trades', ['ticker'], unique=False)
    op.create_index(op.f('ix_insider_trades_trade_date'), 'insider_trades', ['trade_date'], unique=False)
    op.create_table('legislation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('congress_number', sa.Integer(), nullable=True),
    sa.Column('introduced_date', sa.Date(), nullable=True),
    sa.Column('last_action_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sectors_affected', sa.JSON(), nullable=True),
    sa.Column('sponsor_name', sa.String(length=255), nullable=True),
    sa.Column('bill_url', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislation_bill_id'), 'legislation', ['bill_id'], unique=True)
    op.create_table('sector_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_cache_ticker'), 'sector_cache', ['ticker'], unique=True)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=30), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('source_trade_ids', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('price_at_detection', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('sector_etf_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_confidence'), 'signals', ['confidence'], unique=False)
    op.create_index(op.f('ix_signals_detected_at'), 'signals', ['detected_at'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_stock_price')
    )
    op.create_index(op.f('ix_stock_prices_date'), 'stock_prices', ['date'], unique=False)
    op.create_index(op.f('ix_stock_prices_ticker'), 'stock_prices', ['ticker'], unique=False)
    op.create_table('legislation_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.String(length=20), nullable=False),
    sa.Column('member_name', sa.String(length=255), nullable=False),
    sa.Column('chamber', sa.String(length=10), nullable=False),
    sa.Column('vote', sa.String(length=10), nullable=False),
    sa.Column('vote_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['legislation.bill_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislation_votes_bill_id'), 'legislation_votes', ['bill_id'], unique=False)
    op.create_index(op.f('ix_legislation_votes_member_name'), 'legislation_votes', ['member_name'], unique=False)
    op.create_index('ix_legvote_bill_member', 'legislation_votes', ['bill_id', 'member_name'], unique=False)
    op.create_table('signal_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('days_elapsed', sa.Integer(), nullable=False),
    sa.Column('price_current', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sector_change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('outperformed', sa.Boolean(), nullable=True),
    sa.Column('signal_played_out', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_performance_check_date'), 'signal_performance', ['check_date'], unique=False)
    op.create_index(op.f('ix_signal_performance_signal_id'), 'signal_performance', ['signal_id'], unique=False)
    op.create_index('ix_sigperf_signal_date', 'signal_performance', ['signal_id', 'check_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sigperf_signal_date', table_name='signal_performance')
    op.drop_index(op.f('ix_signal_performance_signal_id'), table_name='signal_performance')
    op.drop_index(op.f('ix_signal_performance_check_date'), table_name='signal_performance')
    op.drop_table('signal_performance')
    op.drop_index('ix_legvote_bill_member', table_name='legislation_votes')
    op.drop_index(op.f('ix_legislation_votes_member_name'), table_name='legislation_votes')
    op.drop_index(op.f('ix_legislation_votes_bill_id'), table_name='legislation_votes')
    op.drop_table('legislation_votes')
    op.drop_index(op.f('ix_stock_prices_ticker'), table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_date'), table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_detected_at'), table_name='signals')
    op.drop_index(op.f('ix_signals_confidence'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_sector_cache_ticker'), table_name='sector_cache')
    op.drop_table('sector_cache')
    op.drop_index(op.f('ix_legislation_bill_id'), table_name='legislation')
    op.drop_table('legislation')
    op.drop_index(op.f('ix_insider_trades_trade_date'), table_name='insider_trades')
    op.drop_index(op.f('ix_insider_trades_ticker'), table_name='insider_trades')
    op.drop_index(op.f('ix_insider_trades_sector'), table_name='insider_trades')
    op.drop_table('insider_trades')
    op.drop_table('event_tags')
    op.drop_index(op.f('ix_etf_flows_sector'), table_name='etf_flows')
    op.drop_index(op.f('ix_etf_flows_etf_ticker'), table_name='etf_flows')
    op.drop_index(op.f('ix_etf_flows_date'), table_name='etf_flows')
    op.drop_table('etf_flows')
    op.drop_index(op.f('ix_dividend_events_ticker'), table_name='dividend_events')
    op.drop_table('dividend_events')
    op.drop_index(op.f('ix_congressional_trades_trade_date'), table_name='congressional_trades')
    op.drop_index(op.f('ix_congressional_trades_ticker'), table_name='congressional_trades')
    op.drop_index(op.f('ix_congressional_trades_member_name'), table_name='congressional_trades')
    op.drop_index('ix_congress_member_ticker', table_name='congressional_trades')
    op.drop_table('congressional_trades')
    op.drop_index(op.f('ix_committee_memberships_member_name'), table_name='committee_memberships')
    op.drop_index(op.f('ix_committee_memberships_committee_code'), table_name='committee_memberships')
    op.drop_table('committee_memberships')
    # ### end Alembic commands ###
